<?php

require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'sir_trevor') . '/sir_trevor.field.inc';


/**
 * Implements hook_menu().
 */
function sir_trevor_menu() {
  $items = array();

  $items['sir-trevor/tweet'] = array(
    'page callback' => 'sir_trevor_tweet',
    'access arguments' => array('access content'),
    'file' => 'sir_trevor.pages.inc'
  );

  $items['sir-trevor/image'] = array(
    'page callback' => 'sir_trevor_image',
    'access arguments' => array('access content'),
    'file' => 'sir_trevor.pages.inc'
  );

  $items['admin/config/content/sir-trevor'] = array(
    'title' => 'Sir Trevor',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sir_trevor_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'sir_trevor.pages.inc'
  );

  return $items;
}

/**
 * Implements hook_libraries_info().
 */
function sir_trevor_libraries_info() {
  $libraries['sir-trevor'] = array(
    'name' => 'Sir Trevor',
    'vendor url' => 'http://madebymany.github.io/sir-trevor-js/',
    'download url' => 'https://github.com/madebymany/sir-trevor-js/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "([0-9a-zA-Z\.-]+)"/',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array('sir-trevor.js'),
      'css' => array('sir-trevor.css', 'sir-trevor-icons.css')
    ),
  );
  $libraries['eventable'] = array(
    'name' => 'Eventable',
    'vendor url' => 'http://madebymany.github.io',
    'download url' => 'https://github.com/madebymany/eventable',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "([0-9a-zA-Z\.-]+)"/',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array('eventable.js')
    ),
  );
  $libraries['underscore'] = array(
    'name' => 'Underscore',
    'vendor url' => 'http://underscorejs.org',
    'download url' => 'https://underscorejs.org',
    'version arguments' => array(
      'file' => 'underscore.js',
      'pattern' => '/Underscore\.js ([0-9a-zA-Z\.-]+)/',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array('underscore.js')
    ),
  );
  return $libraries;
}

/**
 * Implements hook_sir_trevor_block_info().
 */
function sir_trevor_sir_trevor_block_info() {
  $blocks = array(
    'text' => array(
      'sir_trevor_name' => 'Text',
      'type' => 'text',
      'name' => t('Text'),
      'markdown' => TRUE
    ),
    'heading' => array(
      'sir_trevor_name' => 'Heading',
      'type' => 'heading',
      'name' => t('Heading'),
      'markdown' => TRUE
    ),
    'quote' => array(
      'sir_trevor_name' => 'Quote',
      'type' => 'quote',
      'name' => t('Quote'),
      'markdown' => TRUE
    ),
    'image' => array(
      'sir_trevor_name' => 'Image',
      'type' => 'image',
      'name' => t('Image')
    ),
    'unordered_list' => array(
      'sir_trevor_name' => 'List',
      'type' => 'list',
      'name' => t('Unordered list'),
      'markdown' => TRUE
    ),
    'video' => array(
      'sir_trevor_name' => 'Video',
      'type' => 'video',
      'name' => t('Video')
    )
  );

  if(module_exists('twitter')) {
    $blocks['tweet'] = array(
      'sir_trevor_name' => 'Tweet',
      'type' => 'tweet',
      'name' => t('Tweet'),
    );
  }

  return $blocks;
}

/**
 * Implements hook_theme().
 */
function sir_trevor_theme() {
  $blocks = sir_trevor_sir_trevor_block_info();
  $theme = array();
  foreach($blocks as $block_name => $block) {
    $markdown = (isset($block['markdown'])) ? $block['markdown'] : FALSE;
    $theme['sir_trevor_' . $block_name] = array(
      'variables' => array('sir_trevor_block' => TRUE,
                           'settings' => array(),
                           'data' => array(),
                           'markdown' => $markdown
                         ),
      'template' => 'sir_trevor_' . $block_name,
      'path' => drupal_get_path('module', 'sir_trevor') .'/theme'
    );
  }
  return $theme;
}

/**
 * Preprocess text blocks to convert from markdown.
 */
function sir_trevor_preprocess(&$variables, $hook) {
  if(!isset($variables['sir_trevor_block']) || !$variables['markdown'] || !$variables['data']->text) {
    return;
  }
  module_load_include('php', 'markdown', 'markdown');
  $variables['data']->text = Markdown($variables['data']->text);
}

/**
 * Implements hook_sir_trevor_loading().
 */
function sir_trevor_sir_trevor_loading() {
  drupal_add_js(drupal_get_path('module', 'sir_trevor') .'/sir_trevor.js');
  drupal_add_css(drupal_get_path('module', 'sir_trevor') .'/sir_trevor.css');
  libraries_load('underscore');
  libraries_load('eventable');
  libraries_load('sir-trevor');
}
